@extends('layouts.landlord-app')

@section('title', 'Assign Tenant to Unit')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ route('landlord.dashboard') }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('landlord.tenant-assignments') }}">Tenant Assignments</a></li>
                        <li class="breadcrumb-item active">Assign Tenant</li>
                    </ol>
                </div>
                <h4 class="page-title">Assign Tenant to Unit</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <!-- Unit Information -->
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <h5 class="card-title">Unit Information</h5>
                            <div class="table-responsive">
                                <table class="table table-borderless">
                                    <tr>
                                        <td><strong>Unit Number:</strong></td>
                                        <td>{{ $unit->unit_number }}</td>
                                    </tr>
                                    <tr>
                                        <td><strong>Apartment:</strong></td>
                                        <td>{{ $unit->apartment->name }}</td>
                                    </tr>
                                    <tr>
                                        <td><strong>Unit Type:</strong></td>
                                        <td>{{ $unit->unit_type }}</td>
                                    </tr>
                                    <tr>
                                        <td><strong>Current Rent:</strong></td>
                                        <td>₱{{ number_format($unit->rent_amount, 2) }}</td>
                                    </tr>
                                    <tr>
                                        <td><strong>Bedrooms:</strong></td>
                                        <td>{{ $unit->bedrooms }}</td>
                                    </tr>
                                    <tr>
                                        <td><strong>Bathrooms:</strong></td>
                                        <td>{{ $unit->bathrooms }}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="alert alert-info">
                                <h6 class="alert-heading">Important Information</h6>
                                <ul class="mb-0">
                                    <li>Tenants must self-register an account before assignment</li>
                                    <li>No automatic credentials are generated by the system</li>
                                    <li>Enter the tenant's registered email to assign them</li>
                                    <li>Documents will need to be uploaded by the tenant</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <!-- Assignment Form -->
                    <form method="POST" action="{{ route('landlord.store-tenant-assignment', $unit->id) }}">
                        @csrf
                        
                        <div class="row">
                            <div class="col-md-6">
                                <h5 class="card-title">Tenant Information</h5>
                                
                                <div class="mb-3">
                                    <label for="email" class="form-label">Tenant Email (must be registered) <span class="text-danger">*</span></label>
                                    <input type="email" class="form-control @error('email') is-invalid @enderror" 
                                           id="email" name="email" value="{{ old('email') }}" required>
                                    @error('email')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>

                                <div class="mb-3">
                                    <label for="phone" class="form-label">Phone Number</label>
                                    <input type="text" class="form-control @error('phone') is-invalid @enderror" 
                                           id="phone" name="phone" value="{{ old('phone') }}">
                                    @error('phone')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>

                                <div class="mb-3">
                                    <label for="address" class="form-label">Current Address</label>
                                    <textarea class="form-control @error('address') is-invalid @enderror" 
                                              id="address" name="address" rows="3">{{ old('address') }}</textarea>
                                    @error('address')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <h5 class="card-title">Lease Information</h5>
                                
                                <div class="mb-3">
                                    <label for="lease_start_date" class="form-label">Lease Start Date <span class="text-danger">*</span></label>
                                    <input type="date" class="form-control @error('lease_start_date') is-invalid @enderror" 
                                           id="lease_start_date" name="lease_start_date" value="{{ old('lease_start_date') }}" required>
                                    @error('lease_start_date')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>

                                <div class="mb-3">
                                    <label for="lease_end_date" class="form-label">Lease End Date <span class="text-danger">*</span></label>
                                    <input type="date" class="form-control @error('lease_end_date') is-invalid @enderror" 
                                           id="lease_end_date" name="lease_end_date" value="{{ old('lease_end_date') }}" required>
                                    @error('lease_end_date')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>

                                <div class="mb-3">
                                    <label for="rent_amount" class="form-label">Monthly Rent <span class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-text">₱</span>
                                        <input type="number" step="0.01" class="form-control @error('rent_amount') is-invalid @enderror" 
                                               id="rent_amount" name="rent_amount" value="{{ old('rent_amount', $unit->rent_amount) }}" required>
                                    </div>
                                    @error('rent_amount')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>

                                <div class="mb-3">
                                    <label for="security_deposit" class="form-label">Security Deposit</label>
                                    <div class="input-group">
                                        <span class="input-group-text">₱</span>
                                        <input type="number" step="0.01" class="form-control @error('security_deposit') is-invalid @enderror" 
                                               id="security_deposit" name="security_deposit" value="{{ old('security_deposit', 0) }}">
                                    </div>
                                    @error('security_deposit')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12">
                                <div class="mb-3">
                                    <label for="notes" class="form-label">Additional Notes</label>
                                    <textarea class="form-control @error('notes') is-invalid @enderror" 
                                              id="notes" name="notes" rows="3" placeholder="Any additional information about this assignment...">{{ old('notes') }}</textarea>
                                    @error('notes')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12">
                                <div class="alert alert-warning">
                                    <h6 class="alert-heading">Required Documents</h6>
                                    <p class="mb-0">The tenant will need to upload the following documents:</p>
                                    <ul class="mb-0 mt-2">
                                        <li>Government ID (Passport, Driver's License, etc.)</li>
                                        <li>Proof of Income (Payslip, Employment Contract, etc.)</li>
                                        <li>Bank Statement (Last 3 months)</li>
                                        <li>Character Reference</li>
                                        <li>Rental History (if applicable)</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12">
                                <div class="d-flex justify-content-end gap-2">
                                    <a href="{{ route('landlord.tenant-assignments') }}" class="btn btn-secondary">Cancel</a>
                                    <button type="submit" class="btn btn-primary" data-bs-toggle="tooltip" data-bs-placement="top" title="Assigning a tenant requires the tenant to already be registered.">
                                        <i class="mdi mdi-account-plus me-1"></i> Assign Tenant
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Set minimum date for lease start date to today
    const today = new Date().toISOString().split('T')[0];
    document.getElementById('lease_start_date').min = today;
    // Enable tooltips
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
    tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl);
    });
    // Update lease end date minimum when start date changes
    document.getElementById('lease_start_date').addEventListener('change', function() {
        const startDate = this.value;
        const endDateInput = document.getElementById('lease_end_date');
        endDateInput.min = startDate;
        // If end date is before start date, clear it
        if (endDateInput.value && endDateInput.value < startDate) {
            endDateInput.value = '';
        }
    });
});
</script>
@endpush 